apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: todo-image-updater
  namespace: argocd
spec:
  namespace: argocd
  commonUpdateSettings:
    updateStrategy: semver
  writeBackConfig:
    method: git
    gitConfig:
      repository: https://github.com/Muntaha369/TODO-k8s.git
      branch: main
  applicationRefs:
    - namePattern: todo          # must match your ArgoCD app name
      images:
        - alias: client
          imageName: muntaha69/todo-client
          manifestTargets:
            kustomize:
              name: muntaha69/todo-client    # must match name in kustomization.yaml
        - alias: server
          imageName: muntaha69/todo-server
          manifestTargets:
            kustomize:
              name: muntaha69/todo-server    # must match name in kustomization.yaml