apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  namespace: todo
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data