apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: todo-server
        image: muntaha69/todo-server
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: MONGODB_URI
          value: mongodb://mongoadmin:root@mongodb:27017/mydb?authSource=admin